auto_move4_node:
  ros__parameters:
    maxSpeed: 25.12
    upperRight: 0x160
    upperLeft: 0x16c
    lowerLeft: 0x164
    lowerRight: 0x168
    velButton: 6
    disButton: 1
    targetX : 25.12
    targetY : 25.12
    # syoukou: 0x154